### PR TITLE
add log module to build aggregate

### PR DESCRIPTION
**Pull request by bpholt**
I noticed the log module wasn't being published, but I found it useful while I was playing with the library. I think with these changes, it should be published during the next release.

### CODE REVIEW

**Comment by tpolecat** [comment]
What's the intent of `MapValuesToJson`?

**Comment by bpholt** [comment]
I was getting deprecation warnings about `mapValues` in Scala 2.13, so I wanted to present a common API that could cross-compiled without warnings.

**Comment by kubukoz** [comment]
oh no, I didn't see this 😢 @bpholt if you don't mind, my solution to the `mapValues` problem involved less code (and zero version-specific code), so maybe let's merge that instead? #74

(also, circe 0.12 got old real quick)

**Comment by bpholt** [comment]
I don’t mind at all! I’ll close this one.

**Pull request closed without merging**
