### PR TITLE
New Relic distributed tracing support

### PR DESCRIPTION
**Pull request by semenodm**
@tpolecat thank you for your library. I think New Relic would be good addition to it. 
I'm going to start using it in my team

### CODE REVIEW

**Comment by tpolecat** [comment]
Hi, sorry for the delay. I will take this PR if you rebase and remove unrelated formatting changes.

**Comment by tpolecat** [comment]
Hm looks like your rebase wasn't correct. Be sure you're rebasing against an up to date master.

**Comment by semenodm** [comment]
@tpolecat should be fine now, i messed up with my remote

**Comment by kubukoz** [comment]
Unrelated formatting changes are less likely to happen if there's a common formatting config ;P

**Pull request merged**
