### PR TITLE
Add log module to root project aggregation

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by kubukoz** [comment]
oof, log4cats isn't published for Scala 2.11 anymore. Do you still want to support that version, @tpolecat?

**Comment by tpolecat** [comment]
Eh, just remove 2.11

**Comment by kubukoz** [comment]
Yes sir :)

**Comment by kubukoz** [comment]
Now the log module complains about Circe. I'll update that as well (0.11 isn't released for 2.13)

**Comment by kubukoz** [comment]
Good to go on my side.

**Pull request merged**
