### PR TITLE
Datadog implementation

### PR DESCRIPTION
**Pull request by tdbgamer**
I made a Datadog implementation based on the Jaeger one. Turned out most of the code could be copied since it all depended on mostly Opentracing types, may makes sense to make a common abstraction out of that at some point (could do it in this PR if you have a way you'd prefer). I only tested the commented out example in the example module, but I'll be testing this out at work tomorrow with a few of our services since this is just about the only way to do opentracing + RPC that I can find for Scala/Cats.

### CODE REVIEW

**Comment by tdbgamer** [comment]
After inspecting other PRs, this could probably be a much less significant change if [this were merged](https://github.com/tpolecat/natchez/pull/79). I'm willing to merge most of that work into my PR and finish cleaning it up if you're okay with that.

**Comment by sbly** [comment]
Hi, just chiming in here. I was actually working on creating a datadog integration PR as well but then found this (they're basically the same). So I am also looking forward to this getting reviewed / merged!

**Comment by tpolecat** [comment]
Hi, sorry for the delay. This looks good. Please pull (I merged this branch with master) and add this project to the `dependsOn` and `aggregate` for the root project. You will also need to do `headerCreate` as the header has change. Thanks!

**Comment by Jacoby6000** [comment]
@tdbgamer are you going to have a chance to look in to this soon? I'll pick it up, fix, and resubmit if not.

**Comment by tdbgamer** [comment]
@Jacoby6000 yeah I was planning to come back and address the comments, but for work I ended up having to just rewrite the library internally cause of time constraints :( if you want to fix it and resubmit, that'd be fine with me.

**Pull request merged**
