### PR TITLE
Trace instances for monad transformers

### PR DESCRIPTION
**Pull request by bplommer**

### CODE REVIEW

**Comment by tpolecat** [comment]
This looks great, thanks! Could you add a compilation test to ensure that the instances for `Trace[Kleisli[F, Span[F]` and the one for `Trace[Kleisl[F: Trace` aren't in conflict? i.e., that they are both accessible?

**Comment by kubukoz** [comment]
Just a suggestion, cats-mtl now contains a `MonadPartialOrder` typeclass that should be useful for lifting. It's an extra dependency, but maybe it's worth considering? Maybe as a separate module away from core?

**Comment by bplommer** [comment]
> Just a suggestion, cats-mtl now contains a `MonadPartialOrder` typeclass that should be useful for lifting. It's an extra dependency, but maybe it's worth considering? Maybe as a separate module away from core?

Interesting - I have an open PR for an mtl module (https://github.com/tpolecat/natchez/pull/166), so could be worth adding there.

**Comment by tpolecat** [comment]
subsumed by #248

**Pull request closed without merging**
