### PR TITLE
Ensure non-null OpenCensus string attribute values

### PR DESCRIPTION
**Pull request by davecromberge**
Handling the error case for an effect attempts to record the underlying
exception's message as well as stack trace as span attributes.
Some exception types such as `java.net.ConnectException` do not have an
exception message, which used to result in null values for the `error.message`
attribute value.

OpenCensus does not permit null values to be recorded as the value
for a string attribute.  This would result in the error stack trace
being polluted with an additional top-level OpenCensus constructor
exception, obscuring the underlying issue.

### CODE REVIEW

**Comment by tpolecat** [comment]
Good catch, thanks! I'll take a PR to fix that if anyone wants to do it.

**Comment by davecromberge** [comment]
@tpolecat Thanks for the quick response.  I introduced this behaviour in an earlier PR, and this PR attempts to fix the problem.  Perhaps you are confusing this with an issue?

**Comment by tpolecat** [comment]
Haha, sorry. I obviously wasn't paying attention. Thanks!

**Comment by tpolecat** [comment]
Travis isn't reporting status anymore but it passed. Need to switch to GH Actions.

**Pull request merged**
