### PR TITLE
add method for creating span from kernel and add current span and kernel to parent of new span

### PR DESCRIPTION
**Pull request by EvgenyAfanasev**
Sometimes I need to continue my span after extraction of it from kafka/database/etc, but also I already have open span and I can't create trace with 2 parents. That's why I want to have the opportunity to create new span with current span and kernel (creating from persistent trace-id). I wrote implementation for all providers but for some of it I may be don't knew API for multiple parents

### CODE REVIEW

**Comment by EvgenyAfanasev** [comment]
> Thanks! Looks good overall. Would you mind resolving conflicts?

Of course, I will make it on weekends

**Comment by mpilquist** [comment]
I'm hoping to release 0.2.0 today and would like to include this PR since it has a binary incompatible change. I'll work on the merge later today if you haven't gotten to it yet. No pressure either way, but just wanted to ensure we weren't both working on the merge simultaneously. Thanks!

**Comment by EvgenyAfanasev** [comment]
> I'm hoping to release 0.2.0 today and would like to include this PR since it has a binary incompatible change. I'll work on the merge later today if you haven't gotten to it yet. No pressure either way, but just wanted to ensure we weren't both working on the merge simultaneously. Thanks!

Hi. I'm currently fix branch and will finish today :)

**Comment by EvgenyAfanasev** [comment]
> 

I have fixed errors. Check it, please

**Comment by EvgenyAfanasev** [comment]
> I'm hoping to release 0.2.0 today and would like to include this PR since it has a binary incompatible change. I'll work on the merge later today if you haven't gotten to it yet. No pressure either way, but just wanted to ensure we weren't both working on the merge simultaneously. Thanks!

change realization of spanR for reducing "copy paste". Check please

**Pull request merged**
